spring:
  application:
    name: demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/demo_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:demo_user}
    password: ${SPRING_DATASOURCE_PASSWORD:demo_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:2s}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080

app:
  redis:
    redisson:
      connection-pool-size: ${REDISSON_CONNECTION_POOL_SIZE:64}
      connection-minimum-idle-size: ${REDISSON_CONNECTION_MIN_IDLE_SIZE:24}
      timeout: ${REDISSON_TIMEOUT:2s}